### ISSUE TITLE
Please add tag support

### ISSUE THREAD

**Issue by aschaal** [esrlabs/centralgithook#5]
- tag in gerrit repo shall be available via Josh
- tag in Josh shall be available in gerrit

Take care about collisions:
- last is best or
- prefix or
- ?

Thank you!

**Comment by gizmomogwai** [comment]
josh?

**Comment by aschaal** [comment]
The official(?) name of the tool. Ask the author for more details... :-)

**Comment by initcrash** [comment]
Read only support for tags has been implemented as of f1c81883b52f847021ead284d71c73704ce0de81
